### ISSUE TITLE
How to get the power & heat info

### ISSUE THREAD

**Issue by EE-LiuYunhao** [project-herakles/Infantry-RTOS-2019#3]
1. Include the head file: referee_system.h. 

1. Invoke the function: get_heat_power(), which: 
    * takes no parameters, and
    * returns the address of the struct powerHeatData.

**Comment by Ericcsr** [comment]
We need hardware for testing the ADC data in flow

**Comment by EE-LiuYunhao** [comment]
Need scoping and testing
